"""A static results page from eval reports (roadmap P9): `python -m abp_agenteval page --out docs/benchmarks/index.html report.json ...`

The page shows every report it is given, side by side, and says plainly what each one *is*:

* a **scripted** report replays golden trajectories, so it verifies that the tools, permissions, security defences and the grading
  work - it says nothing about how good any model is;
* a **live** report ran a real model on the same tasks and is the only kind that compares models. There must be live reports
  from more than one model before the page is a comparison, and it says when there is not.

Nothing on the page compares ABP with Claude Code, OpenCode or any other product: those were not run here. Each report keeps
its date and its task list, and a task a model failed is listed with the reason, not hidden in a percentage."""
from __future__ import annotations

import html
import json
import sys
import time
from pathlib import Path

CSS = """
:root { --bg:#fff; --fg:#1b1b1b; --muted:#666; --line:#ddd; --ok:#1a7f37; --bad:#b42318; --warn:#9a6700; }
@media (prefers-color-scheme: dark) { :root { --bg:#111; --fg:#e6e6e6; --muted:#9a9a9a; --line:#333; --ok:#4ac26b; --bad:#f97066; --warn:#e3b341; } }
body { background:var(--bg); color:var(--fg); font:15px/1.5 system-ui, sans-serif; max-width:1000px; margin:2rem auto; padding:0 16px; }
h1 { font-size:1.5rem } h2 { font-size:1.15rem; margin-top:2rem } table { border-collapse:collapse; width:100%; font-size:.9rem }
th, td { border-bottom:1px solid var(--line); padding:.35rem .5rem; text-align:left; vertical-align:top } th { color:var(--muted); font-weight:600 }
.ok { color:var(--ok) } .bad { color:var(--bad) } .warn { color:var(--warn) } .muted { color:var(--muted) } .note { border-left:3px solid var(--warn); padding:.2rem .8rem; margin:1rem 0 }
"""


def _esc(v) -> str:
    return html.escape(str(v))


def _kind(report: dict) -> str:
    return "live" if report.get("mode") == "live" else "scripted"


def render_html(reports: list[dict], *, title: str = "ABP agent evaluation results") -> str:
    live_models = sorted({r["model"] for r in reports if _kind(r) == "live"})
    out = [f"<!doctype html><html lang=en><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'>"
           f"<title>{_esc(title)}</title><style>{CSS}</style></head><body><h1>{_esc(title)}</h1>"]
    if len(live_models) < 2:
        out.append("<div class=note><strong>This is not a model comparison.</strong> "
                   + ("No live run is included." if not live_models else f"Only one model ({_esc(live_models[0])}) has a live run.")
                   + " Scripted results verify ABP's tools, permission checks, security defences and grading; they say nothing about how good any model "
                     "is. Nothing here compares ABP with Claude Code, OpenCode, Hermes, OpenClaw or any other product: they were not run.</div>")
    out.append("<h2>Summary</h2><table><tr><th>Run</th><th>Mode</th><th>Model</th><th>Passed</th><th>Score</th><th>Tokens</th><th>When</th></tr>")
    for i, r in enumerate(reports, 1):
        when = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime(r.get("when", 0))) if r.get("when") else ""
        out.append(f"<tr><td>{i}</td><td class={'ok' if _kind(r) == 'live' else 'muted'}>{_kind(r)}</td><td>{_esc(r['model'])}</td>"
                   f"<td>{r['passed']}/{r['total']}</td><td>{r['score']}%</td><td>{r['tokens']}</td><td>{_esc(when)}</td></tr>")
    out.append("</table>")
    ids = sorted({x["id"] for r in reports for x in r["results"]})
    titles = {x["id"]: (x.get("title", ""), x.get("category", "")) for r in reports for x in r["results"]}
    out.append("<h2>Tasks</h2><table><tr><th>Task</th><th>Category</th>" + "".join(f"<th>Run {i}</th>" for i in range(1, len(reports) + 1)) + "</tr>")
    for tid in ids:
        cells = []
        for r in reports:
            hit = next((x for x in r["results"] if x["id"] == tid), None)
            cells.append("<td class=muted>-</td>" if hit is None else
                         f"<td class={'ok' if hit['passed'] else 'bad'}>{'pass' if hit['passed'] else 'FAIL'}</td>")
        out.append(f"<tr><td>{_esc(tid)}<div class=muted>{_esc(titles[tid][0])}</div></td><td>{_esc(titles[tid][1])}</td>{''.join(cells)}</tr>")
    out.append("</table>")
    failures = [(i, x) for i, r in enumerate(reports, 1) for x in r["results"] if not x["passed"]]
    if failures:
        out.append("<h2>Failures</h2><table><tr><th>Run</th><th>Task</th><th>Why</th></tr>")
        for i, x in failures:
            why = "; ".join(f"{c['name']}: {c['detail']}" for c in x.get("checks", []) if not c["ok"]) or x.get("error", "")
            out.append(f"<tr><td>{i}</td><td>{_esc(x['id'])}</td><td>{_esc(why)}</td></tr>")
        out.append("</table>")
    out.append("<p class=muted>Generated by <code>python -m abp_agenteval page</code>. Each task's graders check files, the reply and the recorded tool calls; "
               "see docs/agents/evals.md.</p></body></html>")
    return "".join(out)


def main(paths: list[str], out: str) -> int:
    reports = []
    for p in paths:
        try:
            reports.append(json.loads(Path(p).read_text(encoding="utf-8")))
        except (OSError, ValueError) as exc:
            print(f"could not read {p}: {exc}", file=sys.stderr)
            return 2
    if not reports:
        print("give at least one report (a --out file from `abp_agenteval run`)", file=sys.stderr)
        return 2
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    Path(out).write_text(render_html(reports), encoding="utf-8")
    print(f"wrote {out}")
    return 0
