"""Write the dashboard API's OpenAPI document to docs/api/openapi.json, and the TypeScript client generated
from it to sdk/typescript/.

    python scripts/export_openapi.py            regenerate both
    python scripts/export_openapi.py --check    exit 1 if either is out of date (for CI)

The spec is produced by the FastAPI app itself, so it is exactly what the running server serves at /openapi.json.
Output is deterministic (sorted keys, no timestamps) so a diff shows real API changes only."""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
SPEC_PATH = ROOT / "docs" / "api" / "openapi.json"
TS_DIR = ROOT / "sdk" / "typescript"
METHODS = ("get", "post", "put", "delete", "patch")


def build_spec() -> dict:
    os.environ.setdefault("DASHBOARD_TOKEN", "spec-generation-only")
    from bot.dashboard.server import build_app

    return build_app().openapi()


def spec_text(spec: dict) -> str:
    return json.dumps(spec, indent=1, sort_keys=True, ensure_ascii=False) + "\n"


def operations(spec: dict) -> list[dict]:
    out = []
    for path, item in sorted(spec.get("paths", {}).items()):
        for method in METHODS:
            op = item.get(method)
            if not op or "operationId" not in op:
                continue
            params = op.get("parameters") or []
            out.append({"id": op["operationId"], "method": method.upper(), "path": path, "summary": op.get("summary", ""),
                        "path_params": [p["name"] for p in params if p.get("in") == "path"],
                        "query_params": [p["name"] for p in params if p.get("in") == "query"],
                        "body": "requestBody" in op})
    return out


def ts_files(spec: dict) -> dict[str, str]:
    ops = operations(spec)
    entries = {}
    for o in ops:                       # each operation is reachable by its generated id and by "METHOD /path"
        info = {k: o[k] for k in ("method", "path", "path_params", "query_params", "body")}
        entries[o["id"]] = info
        entries[f"{o['method']} {o['path']}"] = info
    table = json.dumps(entries, indent=1, sort_keys=True)
    js = f"""// Generated by scripts/export_openapi.py from docs/api/openapi.json. Do not edit by hand.
// A small client for the ABP dashboard API: any operation by its OpenAPI operationId, plus fetch-based plumbing.
// Works in Node 18+ and browsers (it uses the global fetch).

export const operations = {table};

export class AbpError extends Error {{
  constructor(status, detail) {{
    super(`${{status}}: ${{typeof detail === "string" ? detail : JSON.stringify(detail)}}`);
    this.status = status;
    this.detail = detail;
  }}
}}

export class AbpClient {{
  /** @param {{string}} baseUrl e.g. http://127.0.0.1:8765  @param {{string}} token the dashboard token or a paired device's key */
  constructor(baseUrl, token = "", fetchImpl = globalThis.fetch) {{
    this.baseUrl = baseUrl.replace(/\\/+$/, "");
    this.token = token;
    this.fetch = fetchImpl;
  }}

  async request(method, path, {{ query, body }} = {{}}) {{
    const url = new URL(this.baseUrl + path);
    for (const [k, v] of Object.entries(query || {{}})) if (v !== undefined && v !== null) url.searchParams.set(k, String(v));
    const headers = {{}};
    if (this.token) headers["X-Dashboard-Token"] = this.token;
    if (body !== undefined) headers["Content-Type"] = "application/json";
    const res = await this.fetch(url, {{ method, headers, body: body === undefined ? undefined : JSON.stringify(body) }});
    const text = await res.text();
    let data = text;
    try {{ data = text ? JSON.parse(text) : null; }} catch (_) {{ /* plain text, e.g. a Markdown export */ }}
    if (!res.ok) throw new AbpError(res.status, data && data.detail !== undefined ? data.detail : data);
    return data;
  }}

  /** Call an operation by "METHOD /path" or its generated operationId: call("GET /api/agent/permissions"),
   *  call("GET /api/export/{{table}}", {{ path: {{ table: "jobs" }} }}). */
  call(operationId, {{ path = {{}}, query, body }} = {{}}) {{
    const op = operations[operationId];
    if (!op) throw new Error(`no operation ${{operationId}}`);
    let url = op.path;
    for (const name of op.path_params) {{
      if (!(name in path)) throw new Error(`${{operationId}} needs path parameter ${{name}}`);
      url = url.replace(`{{${{name}}}}`, encodeURIComponent(path[name])).replace(`{{${{name}}:path}}`, path[name]);
    }}
    return this.request(op.method, url, {{ query, body }});
  }}

  modelInfo(provider, model) {{ return this.request("GET", "/api/models/info", {{ query: {{ provider, model }} }}); }}
  modelUsage(days = 1) {{ return this.request("GET", "/api/models/usage", {{ query: {{ days }} }}); }}
  permissions() {{ return this.request("GET", "/api/agent/permissions"); }}
  exportSession(sessionKey, format = "md") {{ return this.request("GET", `/api/agent/sessions/${{sessionKey}}/export`, {{ query: {{ format }} }}); }}
}}
"""
    ids = " | ".join(json.dumps(k) for k in sorted(entries))
    dts = f"""// Generated by scripts/export_openapi.py. Do not edit by hand.
export type OperationId = {ids};

export interface OperationInfo {{ method: string; path: string; path_params: string[]; query_params: string[]; body: boolean }}
export const operations: Record<OperationId, OperationInfo>;

export class AbpError extends Error {{ status: number; detail: unknown; constructor(status: number, detail: unknown) }}

export class AbpClient {{
  constructor(baseUrl: string, token?: string, fetchImpl?: typeof fetch);
  request(method: string, path: string, opts?: {{ query?: Record<string, unknown>; body?: unknown }}): Promise<any>;
  call(operationId: OperationId, opts?: {{ path?: Record<string, string | number>; query?: Record<string, unknown>; body?: unknown }}): Promise<any>;
  modelInfo(provider: string, model: string): Promise<any>;
  modelUsage(days?: number): Promise<any>;
  permissions(): Promise<any>;
  exportSession(sessionKey: string, format?: "md" | "json"): Promise<any>;
}}
"""
    package = json.dumps({"name": "abp-sdk", "version": "0.1.0", "type": "module", "main": "abp.mjs", "types": "abp.d.ts",
                          "description": "Client for the ABP dashboard API (generated)", "license": "UNLICENSED", "private": True}, indent=2) + "\n"
    return {"abp.mjs": js, "abp.d.ts": dts, "package.json": package}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail if the committed files differ from what would be generated")
    args = ap.parse_args(argv)
    spec = build_spec()
    wanted = {SPEC_PATH: spec_text(spec), **{TS_DIR / name: text for name, text in ts_files(spec).items()}}
    stale = [p for p, text in wanted.items() if not p.exists() or p.read_text(encoding="utf-8").replace("\r\n", "\n") != text]
    if args.check:
        for p in stale:
            print(f"out of date: {p.relative_to(ROOT)}", file=sys.stderr)
        return 1 if stale else 0
    for p, text in wanted.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {len(wanted)} files ({len(spec['paths'])} paths)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
